### PR TITLE
fix(ts_utils): fix swap_nodes after get_node_text change

### LINKED ISSUE #2849: Statusline is broken
### Describe the bug

There are three issues with this API
1) it returns `\n` because of recent changes. That will break my statusline plugin as the statusline height is 1. It can not display multiple lines
2) Too much info to be useful
3) get_node_text from `ts_query` may be broken.

### To Reproduce

Take following code as an example:
```lua
-- Trim spaces and opening brackets from end
local transform_line = function(line)
  return line:gsub("%s*[%[%(%{]*%s*$", "")
end
```
When I put cursor on `return` and run
```lua
lua print(require'nvim-treesitter').statusline())
```
I got
```lua
 function(line)\n\treturn line:gsub("%s*[%[%(%{]*%s*$", "")\nend
```
This is too much info for a status to display.

### Expected behavior

It used to return `function(line)`

The root cause is using 
```lua
vim.treesitter.query.get_node_text()
```

https://github.com/nvim-treesitter/nvim-treesitter/blob/bd2f5d770d0a98b1d89bb95dab7ca396b01ce1fe/lua/nvim-treesitter.lua#L37

I think it used to be ts_utils.get_node_text()

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.14.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - java           x ✓ . ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: java(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2028
    java(highlights) is concatenated from the following files:
    | [ERROR]:"/home/ray/.local/share/nvim/site/pack/packer/opt/nvim-treesitter/queries/java/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2028
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1400-g233014f92
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ray

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fsouza**
After some discussion, it looks like the easiest thing to do for now is
to keep a private copy of get_node_text (just to skip the deprecation
message) and invoke that, until core provides an equivalent function
that can return the node content in a table representing the node
"lines".

Also fixes the statusline.

Fix #2849.

### CODE REVIEW

File: lua/nvim-treesitter/ts_utils.lua [hunk 1]
```diff
@@ -360,25 +360,28 @@ function M.swap_nodes(node_or_range1, node_or_range2, bufnr, cursor_to_second)
       range1["end"].line < range2.start.line
       or (range1["end"].line == range2.start.line and range1["end"].character < range2.start.character)
     then
-      line_delta = #text2 - #text1
+      line_delta = (range2["end"].line - range2["start"].line + 1) - (range1["end"].line - range1["start"].line + 1)
     end
 
     if range1["end"].line == range2.start.line and range1["end"].character < range2.start.character then
+      local lines1 = vim.split(text1, "\n")
+      local lines2 = vim.split(text2, "\n")
```
Comment (fsouza) [inline lua/nvim-treesitter/ts_utils.lua:368]: this isn't the fastest, could try to figure out something faster (like counting the characters from the end of the string to a `\n`), but this is very much of an edge case and I don't expect people to be swapping very large nodes, so the extra memory usage should be ok? (famous last words)

Comment (fsouza) [reply lua/nvim-treesitter/ts_utils.lua:368]: Pattern matching would also work, something like:

```lua
local function length_last_line(str)
  if str == "" then
    return 0
  end
  local first, last = string.find(str, "\n?[^\n]+$")
  return last - first
end

-- ...

local length_last_line1 = length_last_line(text1)
local length_last_line2 = length_last_line(text2)
```

Though that isn't super readable 🤷

Comment (theHamsta) [reply lua/nvim-treesitter/ts_utils.lua:368]: Wasn't aware that get_node_text wasn't no longer working on lines. Seems a bit odd for me to join the lines just to split them afterwards which occurs in many occasions of get_node_text. Maybe we should just revert it. Can't you get the #lines from the node range?

Comment (theHamsta) [reply lua/nvim-treesitter/ts_utils.lua:368]: You should get the length of the last line by looking at the start/end cols of the node range

Comment (fsouza) [reply lua/nvim-treesitter/ts_utils.lua:368]: > You should get the length of the last line by looking at the start/end cols of the node range

OMG that's right. Sorry I'll fix that later today.

Comment (fsouza) [reply lua/nvim-treesitter/ts_utils.lua]: Fixed it. I feel like it'd be cool to have some tests for this, but I assume that would require mocking get_node_text. Let me know if you have any thoughts on this.

Comment (theHamsta) [reply lua/nvim-treesitter/ts_utils.lua]: You can have a look on the tests that were there when we removed `get_node_text?

File: lua/nvim-treesitter/ts_utils.lua [hunk 2]
```diff
@@ -337,18 +337,26 @@ function M.memoize_by_buf_tick(fn, options)
   end
 end
 
+local function length_last_line(range)
+  if range.start.line == range["end"].line then
+    return range["end"].character - range.start.character + 1
+  else
+    return range["end"].character + 1
+  end
+end
```
Comment (theHamsta) [inline lua/nvim-treesitter/ts_utils.lua:346]: I'm not sure whether this is correct. When end col = 0 then get_node_text would not include this last line also the + 1 shouldn't be necessary. As `get_vim_range` shows it is apparently not possible to get the length of the last line without accessing the actual text. Probably you pattern matching approach would be better (or return to ye old get_node_text)

Comment (fsouza) [reply lua/nvim-treesitter/ts_utils.lua:346]: My thought with +1 is that ranges are zero-based and end-inclusve? So, for example, if range.end.character is 12, it means it includes characters 0, 1, 2, ..., 12, i.e. 13 characters.

I see what you mean though, range.end.character may be "out of bounds"? (accessing the 0th element in an empty array is an out of bound errors, but it seems that that's expected to work here?)

Are you saying that for a range like `{start = {line = 1, col = 0}, end = {line = 10, col = 0}}`, get_node_text will only return 9 lines? In that case this won't work either: https://github.com/nvim-treesitter/nvim-treesitter/pull/2838/files#diff-ee62282252e6dfba5eebd5b1a5a1ff9df64f01392723b3044965d5c7469e9915R371

Comment (fsouza) [reply lua/nvim-treesitter/ts_utils.lua:346]: but yeah it sounds like the best solution for now is to keep nvim-treesitter's version of get_node_text that returns a table with the lines instead of using vim.treesitter.query.get_node_text?

Comment (theHamsta) [reply lua/nvim-treesitter/ts_utils.lua:346]: @clason are you fine with reverting? Most plugin can do the switch easily while for some application the join/split is just a needless round trip. For swap it's not critical since swap is slow due to the queries finding the swap objects

**Comment by clason** [comment]
> @clason are you fine with reverting? Most plugin can do the switch easily while for some application the join/split is just a needless round trip. For swap it's not critical since swap is slow due to the queries finding the swap objects

I've already re-added the old implementation so plugins are no longer broken.

However, I don't like having two almost-but-not-entirely identical functions _with the same name_ here and upstream. I would prefer if we would either

1. add an option table with `table=true` (default `false`) to the upstream function, or
2. rename the function here into something that makes the difference clearer.

To make absolutely sure: the only difference (beside the `bufnr` argument, which is a _good_ change in any case) is the question of returning a table vs a concatenated string?

**Comment by theHamsta** [comment]
The `bufnr` was there before but it was optional. I think the return value is the only difference.

**Comment by clason** [comment]
Then my (strong) preference would be option 1.

**Comment by fsouza** [comment]
> Then my (strong) preference would be option 1.

That would make nvim-treesitter dependent on nightly though. Is that ok?

**Comment by clason** [comment]
I think that's something that can be backported to 0.7.1 in this case, so it wouldn't be too bad. We still have the old code, anyway, so we can refactor this into a private method that we can call here without deprecation warnings until the release.

**Comment by fsouza** [comment]
@clason @theHamsta I just pushed an updated commit making use of a private copy of get_node_text that won't print the deprecation warning. I also rewrote the commit message to describe the new change. Let me know what yall think of that.

**Comment by fsouza** [comment]
Sorry, fixed the linter violation 🙈

**Comment by fsouza** [comment]
@clason @theHamsta friendly ping :D

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
While you're at it, could you also change the use in https://github.com/nvim-treesitter/nvim-treesitter/blob/bd2f5d770d0a98b1d89bb95dab7ca396b01ce1fe/lua/nvim-treesitter.lua#L37
back to the internal function? Should be 
```lua
get_node_text(node)[1]
```
with the internal function. (Probably best to move this into `ts_util` and expose it as a private function.)

This would then close #2849

**Comment by clason** [comment]
Yes, and marked `---@private` for good measure.

**Comment by fsouza** [comment]
> Yes, and marked `---@private` for good measure.

Cool, should be good to go now!

**Comment by fsouza** [comment]
@clason do you think we can merge or should we wait for @theHamsta?

**Comment by clason** [comment]
I'd like to wait for @theHamsta just to make sure. I'd prefer fixing it once ;)

**Comment by AckslD** [comment]
Sorry if I might be misunderstanding something but one other issue seems to be that `swap_nodes` takes a node or range which is used by `treesitter-textobjects` [here](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/lua/nvim-treesitter/textobjects/swap.lua#L19). When this gets passed to `get_node_text` it breaks since a if it's a range calling the method `:start` clearly doesn't work.

**Comment by fsouza** [comment]
> Sorry if I might be misunderstanding something but one other issue seems to be that `swap_nodes` takes a node or range where the latter is used by `treesitter-textobjects` [here](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/lua/nvim-treesitter/textobjects/swap.lua#L19). When this gets passed to `get_node_text` it breaks since a if it's a range calling the method `:start` clearly doesn't work.

As far as I can tell this PR is reverting the behavior back to what it used to be. Is nvim-treesitter-textobjects also failing if you use this PR?

**Comment by AckslD** [comment]
@fsouza It does indeed work with this branch :+1: Just looking at the code I couldn't figure out how ranges are handled in `swap_nodes`

**Comment by fsouza** [comment]
> @fsouza It does indeed work with this branch 👍 Just looking at the code I couldn't figure out how ranges are handled in `swap_nodes`

it's handled in get_node_range (which is called from get_node_text): https://github.com/nvim-treesitter/nvim-treesitter/blob/4a53674d5b90ab959322d381121c16072b00ac4b/lua/nvim-treesitter/ts_utils.lua#L301-L307

**Review by theHamsta — APPROVED** [review]
