### PR TITLE
shell: respect shellslash option on Windows

### LINKED ISSUE #2844: Can't install parser with shellslash option enabled on Windows
### Describe the bug

This error is shown when attempting to install language parser with `shellslash` option enabled:

```
nvim-treesitter[lua]: Failed to execute the following command:
{
  cmd = "cmd",
  opts = {
    args = { "/C", "if", "exist", "C:\\Users\\user\\AppData\\Local/nvim-data\\tree-sitter-lua", "rmdir", "/s", "/q", "C:\\Users\\user\\AppData\\Local/nvim-data\\tree-sitter-lua" },
    stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
    }
  }
}
Invalid switch - "nvim-data\tree-sitter-lua".^M
```

### To Reproduce

Example with `lua`:
1. `:set shellslash`
2. `:TSInstall lua`
3. Press `y` to reinstall if `lua` is already installed.
4. Notice execution of command via `cmd` (`rmdir`, see `Describe the bug` section for full message) will fail with message: `Invalid switch - "nvim-data\tree-sitter-lua".^M`

### Expected behavior

Installation and update of language parsers should be possible no matter what is the setting of  `shellslash` option.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc.exe (GCC) 10.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - gdscript       ✓ ✓ . ✓ ✓ 
  - cooklang       ✓ . . . . 
  - rst            ✓ ✓ . . ✓ 
  - slint          ✓ . . ✓ . 
  - godot_resource ✓ ✓ ✓ . . 
  - css            ✓ . ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - vala           ✓ . . . . 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - d              ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - r              ✓ ✓ . ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - gleam          ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - wgsl           ✓ . ✓ . . 
  - todotxt        ✓ . . . . 
  - fortran        ✓ . ✓ ✓ . 
  - eex            ✓ . . . ✓ 
  - rego           ✓ . . . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - elvish         ✓ . . . ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - elm            ✓ . . . ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - ocamllex       ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - solidity       ✓ . . . . 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - norg           . . . . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - hack           ✓ . . . . 
  - scala          ✓ . ✓ . ✓ 
  - foam           ✓ ✓ ✓ ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - scss           ✓ . . ✓ . 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - astro          ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - fusion         ✓ ✓ ✓ ✓ . 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - dot            ✓ . . . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - erlang         . . . . . 
  - pug            ✓ . . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - help           ✓ . . . . 
  - gomod          ✓ . . . ✓ 
  - swift          ✓ ✓ . . . 
  - yang           ✓ . ✓ . . 
  - hocon          ✓ . . . ✓ 
  - latex          ✓ . ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - llvm           ✓ . . . . 
  - regex          ✓ . . . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - http           ✓ . . . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - scheme         ✓ . ✓ . ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - haskell        ✓ . . . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - gowork         ✓ . . . ✓ 
  - perl           ✓ . ✓ . . 
  - vue            ✓ . ✓ ✓ ✓ 
  - lalrpop        ✓ ✓ . . . 
  - prisma         ✓ . . . . 
  - ledger         ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113

Features: -acl +iconv +tui
```

### Additional context

`lua` is just an example, it seems like no language parser can be installed with `shellslash` option enabled.

### PR DESCRIPTION
**Pull request by tajtiattila**
Fixes #2844 #1965

### CODE REVIEW

**Comment by tajtiattila** [comment]
Apparently there are outstanding problems with this patch. Nvim-treesitter reported success after installing languages, but nothing seems to be installed, and the installation process starts again every time Neovim is started.

**Comment by tajtiattila** [comment]
I found the cause of the second problem with `shellslash`, it is the `is_installed()` function in install.lua. With `shellslash` enabled on Windows the plugin paths end up having different path separators, eg.
install_dir = "C:\\path\\to\\installdir/parser"
abspath = "C:/path/to/installdir/parser/rust.so"
so the comparison with `vim.startswith()` always returned false.

This means all parsers defined in `ensure_installed` were recompiled every time Neovim started.

I've added a `clean_path()` method for use in `is_installed()`, this seems to have fixed this issue.

File: lua/nvim-treesitter/shell_command_selectors.lua [hunk 1]
```diff
@@ -153,7 +164,7 @@ function M.select_mv_cmd(from, to, cwd)
     return {
       cmd = "cmd",
       opts = {
-        args = { "/C", "move", "/Y", from, to },
+        args = { "/C", "move", "/Y", cmdpath(from), cmdpath(to) },
```
Comment (theHamsta) [inline lua/nvim-treesitter/shell_command_selectors.lua:167]: @tajtiattila can this normalization happen at the beginning of the functions? Otherwise it is easy to forget to add `cmdpath` when more commands are added.

**Comment by theHamsta** [comment]
Thank you a lot! I think I ran into this issue this morning.

File: lua/nvim-treesitter/shell_command_selectors.lua (hunk 1 above)
Comment (theHamsta) [reply lua/nvim-treesitter/shell_command_selectors.lua:167]: Hmm, but maybe is the `cmdpath` for `"cmd"` invocation also a reminder to remember that. I'm fine with either solution that you prefer!

**Review by theHamsta — APPROVED** [review]

File: lua/nvim-treesitter/shell_command_selectors.lua (hunk 1 above)
Comment (tajtiattila) [reply lua/nvim-treesitter/shell_command_selectors.lua:167]: I believe someone adding new commands using `cmd.exe` will stumble upon `cmdpath` and realize it is needed for paths.

I thought about better ways to do it, but I couldn't find any. Perhaps commands could use powershell, but I don't know much about it. I always use bash, which is why I prefer using `shellslash` in (Neo)Vim.
