### PR TITLE
indents(php): don't use aligned_indent for php

### LINKED ISSUE #2497: php indentation is broken after #2333
### Describe the bug

Some indentation in php is broken since the merge of this PR.

- <https://github.com/nvim-treesitter/nvim-treesitter/pull/2333>

### To Reproduce

1. Enter `o` in the `Route::get('/', function () {` line.

    ```php
    <?php
    
    use Illuminate\Support\Facades\Route;
    
    Route::get('/', function () {
        return view('welcome');
    });
    ```

2. The cursor is at the `|` position. Unfortunately, the indentation is severely broken. 
    ```php
    <?php
    
    use Illuminate\Support\Facades\Route;
    
    Route::get('/', function () {
                   |
        return view('welcome');
    });
    ```

---

**[NG] DEMO (mp4)**:

https://user-images.githubusercontent.com/188642/153112070-85283df0-9460-4020-91df-1d3c2797432b.mp4

### Expected behavior

I reverted the changes in `queries/php/indents.scm` and try it. <https://github.com/nvim-treesitter/nvim-treesitter/commit/992926ab99e1c6e929e3a1d2873daac8a193907e>

Correct indentation!

```php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    |
    return view('welcome');
});
```

**[OK] DEMO (mp4)**:

https://user-images.githubusercontent.com/188642/153112673-c188d0b1-1281-430d-b24d-a2211eae3703.mp4

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - prisma         ✓ . . . . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ . . ✓ 
  - llvm           ✓ . . . . 
  - ledger         ✓ . ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - ql             ✓ ✓ . ✓ ✓ 
  - pug            ✓ . . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - comment        ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - erlang         . . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - eex            ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - vala           ✓ . . . . 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - http           ✓ . . . ✓ 
  - hocon          ✓ . . . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - scss           ✓ . . ✓ . 
  - zig            ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - scala          ✓ . ✓ . ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - perl           ✓ . . . . 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - r              ✓ ✓ . ✓ . 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1040-ge16ec0be2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by theHamsta**
Fixes #2497

Can you test this please @yaegassy?

### CODE REVIEW

File: tests/indent/php/issue-2497.php [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+use Illuminate\Support\Facades\Route;
+
+Route::get('/', function () {
+    return view('welcome');
+});
+
+Route::get(
+    '/',
+    1,
+    aaaaaaaaaaaaaaaaaaaaaaaaa,
```
Comment (theHamsta) [inline tests/indent/php/issue-2497.php:12]: it's not nice that it would indent with 0 when ")" is not there...

**Comment by yaegassy** [comment]
I have tested it. I was able to check that the issues in this issue have been resolved.

**Review by kyazdani42 — APPROVED** [review]
