### PR TITLE
perf: cache has_query_files: fixes TS slowness

### LINKED ISSUE #1267: Input lag on cursor movement and edits when a buffer has a lot of injections (like comments)
**Describe the bug**

When a buffer has a considerably large amount of comments (500 for the gif example) treesitter slows down significantly when moving cursor with `j` and `k`.

**To Reproduce**

1. Create a new file `lagtest.lua`
2. Insert any comments into the buffer (500 lines should be enough).
3. Enable treesitter highlighting with `TSBufEnable highlight`.
3. Go to the top of the buffer and notice the lag when moving the cursor with `k` and `j`.
4. Go to the bottom of the buffer and notice that there is no lag.

**Expected behavior**

No input lag on cursor movement.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

```
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v12.18.4 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - java           ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . 
  - c              ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - zig            ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ 
  - latex          ✓ . ✓ . 
  - go             ✓ ✓ ✓ ✓ 
  - ledger         ✓ . ✓ ✓ 
  - nix            ✓ ✓ ✓ . 
  - teal           ✓ ✓ ✓ ✓ 
  - ocaml_interface✓ ✓ ✓ . 
  - php            ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . 
  - javascript     ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ 
  - kotlin         ✓ . . . 
  - r              ✓ ✓ . . 
  - svelte         ✓ . ✓ ✓ 
  - comment        ✓ . . . 
  - verilog        ✓ ✓ ✓ . 
  - jsdoc          ✓ . . . 
  - regex          ✓ . . . 
  - query          ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ 
  - fennel         ✓ ✓ . . 
  - html           ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ 
  - glimmer        ✓ . . . 
  - vue            ✓ . ✓ . 
  - rust           ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - clojure        ✓ ✓ . . 
  - rst            ✓ ✓ . . 
  - css            ✓ . ✓ ✓ 
  - beancount      ✓ . ✓ . 
  - c_sharp        ✓ . . . 
  - ruby           ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ . . 
  - tsx            ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1285-g0150cc416
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.5.0~dev.1285.g0150cc416/x86_64-redhat-linux-gnu/config -I/builddir/build/BUILD/neovim-0.5.0~dev.1285.g0150cc416/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.5.0~dev.1285.g0150cc416/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.5.0~dev.1285.g0150cc416/x86_64-redhat-linux-gnu/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Also tried this with ruby with same results. The more there are comments, the worse the lag (comes to a literal crawl on 10k lines)

I realize that 10k of comments is unrealistic, but it begins to be noticeably laggy on 200 lines. On the gif take note of current line numbers, and how much it takes for the input to catch up when at the start of buffer compared to key screencapture.

tree-crawl-500

Edit: typos

### LINKED ISSUE #1438: Tree-sitter based folding make substitution slow in Neovim config
**Describe the bug**

Set
```lua
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr   = "nvim_treesitter#foldexpr()
```
make substitution incredibly laggy. But this only happen when edit Neovim dotfiles. 

**To Reproduce**

1. Do increment search and replace with `%s/old/new`
2. It took many seconds to incrementally replace `old` 
3. Only happen with Neovim lua-based config
4. It's working OK with other files which are not located in dotfiles 

**Expected behavior**

Search and replace should be working as normal

**Output of `:checkhealth nvim_treesitter`**

<details>

<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v12.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - gdscript       ✓ ✓ . . ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - vue            ✓ . ✓ . ✓ 
  - latex          ✓ . ✓ . . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - nix            ✓ ✓ ✓ . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - cuda           ✓ ✓ ✓ ✓ . 
  - fennel         ✓ ✓ . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - kotlin         ✓ . . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - erlang         . . . . . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - elixir         ✓ ✓ . ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - ocamllex       ✓ . . . ✓ 
  - c_sharp        ✓ . ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - julia          ✓ ✓ ✓ . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - gomod          ✓ . . . . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1444-gc1120ad0e
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210626-28007-f5726v/build/config -I/tmp/neovim-20210626-28007-f5726v/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210626-28007-f5726v/build/src/nvim/auto -I/tmp/neovim-20210626-28007-f5726v/build/include
Compiled by babygau@babygau.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c1120ad_2/share/nvim"

Run :checkhealth for more info

</code>
</details>

### PR DESCRIPTION
**Pull request by folke**
Right now, `has_query_files` with `nvim_get_runtime_file` is being executed a lot, which slows down TreeSitter code quite a bit. Especially when folding is enabled,

This PR caches the result so subsequent calls are instant.

Fixes #1438 
Fixes #1267

### CODE REVIEW

File: lua/nvim-treesitter/query.lua [hunk 1]
```diff
@@ -61,9 +61,14 @@ local function runtime_queries(lang, query_name)
   return api.nvim_get_runtime_file(string.format('queries/%s/%s.scm', lang, query_name), true) or {}
 end
 
+local query_files_cache = {}
```
Comment (theHamsta) [inline lua/nvim-treesitter/query.lua:64]: Nice! We have a cache invalidation mechanism that is triggered when a user saves a queries/lang/xx.scm file. Can you have a look whether this could also apply here (e.g. when user creates a new query file It is found)

**Review by theHamsta — APPROVED** [review]

File: lua/nvim-treesitter/query.lua (hunk 1 above)
Comment (folke) [reply lua/nvim-treesitter/query.lua:64]: @theHamsta done!

did some further testing and this is really a massive performance improvement.

Previously I had quite some lagging when editing neovim runtime files, and  all of that is completelty gone now!

Comment (folke) [reply lua/nvim-treesitter/query.lua:64]: I'm pretty sure a lot of other issues related to slowness can probably be closed as well

**Review by theHamsta — APPROVED** [review]

**Comment by theHamsta** [comment]
Thanks really great work!

File: lua/nvim-treesitter/query.lua [hunk 2]
```diff
@@ -61,9 +61,16 @@ local function runtime_queries(lang, query_name)
...
 function M.has_query_files(lang, query_name)
-  local files = runtime_queries(lang, query_name)
-  return files and #files > 0
+  if not query_files_cache[lang] then
+    query_files_cache[lang] = {}
+  end
+	if query_files_cache[lang][query_name] == nil then
```
Comment (vigoux) [inline lua/nvim-treesitter/query.lua:69]:
```suggestion
	if not query_files_cache[lang][query_name] then
```

**Review by vigoux — CHANGES_REQUESTED** [review]

File: lua/nvim-treesitter/query.lua (hunk 2 above)
Comment (folke) [reply lua/nvim-treesitter/query.lua:69]: It should be a check for `nil`, since if it is `false` we also don't need to check

Comment (folke) [reply lua/nvim-treesitter/query.lua:69]: either we already checked, or the file esxists, or it doesn;t exist

Comment (vigoux) [reply lua/nvim-treesitter/query.lua:69]: Oh yeah I see

**Review by vigoux — APPROVED** [review]

**Comment by KarlWithK** [comment]
I really wanted to say thank you for this PR. I instantly noticed the difference in starting up files, moving my cursor, using plugins that deal with text, and folds. I was always told that treesitter was faster than the regular regex highlight expressions, but due to serveal issues that I didn't know existed until this was fixed I thought it was just talk. Now with this significant speedup, I can see why everyone is invested with treesitter.

**Comment by folke** [comment]
@KarlWithK thanks :-) There's still issues with the folding though. I've disabled it for now. to make it useable it should be reimplemented in another way, by programmatically creating folds. The back and forth between vimscript and Lua within foldexpressins is too slow (at least for now)

**Comment by stsewd** [comment]
@folke I did this experiment to avoid the lua/vimscript back and forth https://github.com/stsewd/nvim-treesitter/tree/cache-folds-vimscript https://github.com/stsewd/nvim-treesitter/commit/989c8c2e31c65329a1805701d54de14fd0c980a1 I didn't see any improvements on my machine, but you can test it if that improve things for you.

**Comment by folke** [comment]
@stsewd just checked your branch and doesn't make a difference. (while it should :) )

Even when I return `0` in the vim fold function, it is still super slow, so probably something that should be fixed in Neovim core.

To test, take a large file like the runtime lua lsp util.lua. And open it from the command line.

Replace the foldexpr function by the code below.

It takes a couple of seconds to open the file. So probably has nothing to do with the Lua bridge.

```vim
function! nvim_treesitter#foldexpr() abort
    return 0
endfunction
```

**Comment by charlescochran** [comment]
Unfortunately, this doesn't seem to fix #1267 for me. Having to disable the comment parser instead.
