### PR TITLE
fix: do `vim.treesitter.start()` on highlight module attach

### LINKED ISSUE #4026: auto_install requires restart or reinstallation for highlighting
### Describe the bug

With `auto_install` enabled, opening a filetype for a language for the first time successfully installs the parser for that language. Although it is installed, it does not highlight the current buffer or other buffers of that filetype. 

### To Reproduce

1. Create a treesitter config such as the following (currently using lazy.nvim, but reproduced with packer.nvim). In particular, have `auto_install` set to `true` and highlights enabled:
```lua
{
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			highlight = {
				enable = true,
			},
		})
	end,
}
```
2. Open a filetype that has not been opened before. Optionally, run `:TSUninstall` first to ensure the parser is not installed.
3. Observe a message such as `[nvim-treesitter] [1/1] Treesitter parser for go has been installed` confirming the parser has been installed, but that highlights are not being applied.
4. Either open a new neovim instance to see highlights applied, or run `TSInstall!` in the current instance to see highlights applied.

### Expected behavior

After the parser is installed automatically, highlights should be visible immediately without having to reinstall the parser or restart neovim.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112"
} ~

Parser/Features         H L F I J
  - lua                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-553+g9be24110f-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by rob@Roberts-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-9be2411/share/nvim"

Run :checkhealth for more info
```

### Additional context

When running `:checkhealth nvim-treesitter`, a parser that has been auto-installed and but is not yet highlighting does not appear in the `Parser/Features` table. After reinstalling or starting a new neovim instance, it does appear.

This bug only seems to occur with auto_install enabled, and does not occur after installing manually with `auto_install` disabled.

### PR DESCRIPTION
**Pull request by theHamsta**
Fixes #4026

I don't know whether this is the right thing (probably not). I was not aware of `vim.treesitter.start()`. When it is invoked somewhere else we should probably just do  `vim.treesitter.start()` when the installation is finished in case the highlight module is enabled.

Probably, the highlight module can be removed entirely when the functionality is managed by Neovim.

### CODE REVIEW

**Comment by clason** [comment]
> Probably, the highlight module can be removed entirely when the functionality is managed by Neovim.

Yes, that's what I've been suggesting for quite a while. (Not that there's a lot in that module; basically just replace the low-level `ts.highlighter` calls with `ts.start()`/`stop()`.)

File: lua/nvim-treesitter/highlight.lua [hunk 1]
```diff
@@ -33,6 +33,7 @@ end
 function M.start(bufnr, lang)
   local parser = parsers.get_parser(bufnr, lang)
   ts.highlighter.new(parser, {})
+  vim.treesitter.start(bufnr, lang)
```
Comment (clason) [inline lua/nvim-treesitter/highlight.lua:36]:
```suggestion
  vim.treesitter.start(bufnr, lang)
```

File: lua/nvim-treesitter/highlight.lua [hunk 2]
```diff
@@ -49,6 +50,7 @@ end
 function M.detach(bufnr)
   M.stop(bufnr)
   enable_syntax(bufnr)
+  vim.treesitter.stop(bufnr)
```
Comment (clason) [inline lua/nvim-treesitter/highlight.lua:53]:
```suggestion
  vim.treesitter.stop(bufnr)
```

File: lua/nvim-treesitter/highlight.lua (hunk 1 above)
Comment (clason) [reply lua/nvim-treesitter/highlight.lua:36]: In fact, that whole function (and `stop()`) can go; just `vim.treesitter.start()` in `attach()` (and similarly for `detach()`).

**Comment by clason** [comment]
Can remove `M.start()` as well -- and probably just inline the `vim.api` call; no need to factor out a one-liner?

**Comment by theHamsta** [comment]
@clason I left it because it was exposed to users.

**Comment by clason** [comment]
But so was `stop()`? But I agree, should remove or at least deprecate it.

**Review by clason — APPROVED** [review]

File: lua/nvim-treesitter/highlight.lua [hunk 3]
```diff
@@ -21,34 +19,36 @@ local function enable_syntax(bufnr)
...
 end
 
 ---@param bufnr integer
 function M.detach(bufnr)
-  M.stop(bufnr)
+  vim.treesitter.stop(bufnr)
   enable_syntax(bufnr)
 end
 
+function M.start(...)
```
Comment (clason) [inline lua/nvim-treesitter/highlight.lua:38]:
```suggestion
---@deprecated
function M.start(...)
```

File: lua/nvim-treesitter/highlight.lua [hunk 4]
```diff
@@ -21,34 +19,36 @@ local function enable_syntax(bufnr)
...
+  vim.notify(
+    "`nvim-treesitter.highlight.start` is deprecated: use `nvim-treesitter.highlight.attach` or `vim.treesitter.start`",
+    vim.log.levels.WARN
+  )
+  M.attach(...)
+end
+
+function M.stop(...)
```
Comment (clason) [inline lua/nvim-treesitter/highlight.lua:46]:
```suggestion
---@deprecated
function M.stop(...)
```

**Review by clason — APPROVED** [review]
