### PR TITLE
Simplify module setup process

### LINKED ISSUE #178: Getting error when trying to use textobjects: `attempt to concatenate local 'query' (a boolean value)`
**Describe the bug**

When trying to configure textobjects, I'm getting the following error whenever I open a Python file (or C/C++):

```
Error executing vim.schedule lua callback: ...plug/nvim-treesitter/lua/nvim-treesitter/textobjects.lua:70: attempt to concatenate local 'query' (a boolean value)
```

Here's the config I tried:

```lua
  local configs = require('nvim-treesitter.configs')
  configs.setup({
    highlight = {enable = false};
    incremental_selection = {
      enable = true;
      keymaps = {
        init_selection = 'gnn';
        node_incremental = '<tab>';
        scope_incremental = 'grc';
        node_decremental = '<s-tab>';
      };
    };
    refactor = {
      smart_rename = {enable = true; keymaps = {smart_rename = 'grr'}};
      navigation = {enable = true; keymaps = {goto_definition = 'gnd'; list_defitinions = 'gnD'}};
    };
    textobjects = {
      enable = true;
      keymaps = {
        af = '@function.outer';
        ['if'] = '@function.inner';
        aC = '@class.outer';
        iC = '@class.inner';
        al = '@block.outer';
        il = '@block.inner';
      };
    };
    ensure_installed = 'all';
}
```

I assume I'm doing something wrong, but I can't really figure out what.

**To Reproduce**

1. Add textobjects to your treesitter config
1. Open a file that has textobjects query (builtin: Python, C & C++)

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## html parser healthcheck
  - OK: html parser found.
  - WARNING: No `locals.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `highlights.scm` found.

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## regex parser healthcheck
  - OK: regex parser found.
  - WARNING: No `locals.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `highlights.scm` found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## nix parser healthcheck
  - OK: nix parser found.
  - WARNING: No `locals.scm` query found for nix
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for nix
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## swift parser healthcheck
  - OK: swift parser found.
  - WARNING: No `locals.scm` query found for swift
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for swift
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## java parser healthcheck
  - OK: java parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## yaml parser healthcheck
  - OK: yaml parser found.
  - WARNING: No `locals.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## elm parser healthcheck
  - OK: elm parser found.
  - WARNING: No `locals.scm` query found for elm
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for elm
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## vue parser healthcheck
  - OK: vue parser found.
  - WARNING: No `locals.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## toml parser healthcheck
  - OK: toml parser found.
  - WARNING: No `locals.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## ruby parser healthcheck
  - OK: ruby parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## ocaml parser healthcheck
  - OK: ocaml parser found.
  - WARNING: No `locals.scm` query found for ocaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for ocaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## go parser healthcheck
  - OK: go parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## scala parser healthcheck
  - OK: scala parser found.
  - WARNING: No `locals.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## haskell parser healthcheck
  - OK: haskell parser found.
  - WARNING: No `locals.scm` query found for haskell
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for haskell
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## json parser healthcheck
  - OK: json parser found.
  - WARNING: No `locals.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `highlights.scm` found.

## markdown parser healthcheck
  - OK: markdown parser found.
  - WARNING: No `locals.scm` query found for markdown
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for markdown
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## css parser healthcheck
  - OK: css parser found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `highlights.scm` found.

## php parser healthcheck
  - OK: php parser found.
  - WARNING: No `locals.scm` query found for php
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for php
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c_sharp parser healthcheck
  - OK: c_sharp parser found.
  - WARNING: No `locals.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `highlights.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## bash parser healthcheck
  - OK: bash parser found.
  - WARNING: No `locals.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `highlights.scm` found.

## tsx parser healthcheck
  - OK: tsx parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## Missing parsers
  - WARNING: Some parsers are not installed:
    julia
    - ADVICE:
      - Install them using `:TSInstall language

</code>
</details>

**Output of `nvim --version`**
```
％ nvim --version
NVIM v0.5.0-593-g1ca67a73c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/fsouza/Projects/os/3/neovim/build/config -I/Users/fsouza/Projects/os/3/neovim/src -I/Users/fsouza/Projects/os/3/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/fsouza/Projects/os/3/neovim/build/src/nvim/auto -I/Users/fsouza/Projects/os/3/neovim/build/include
Compiled by fsouza@fsouza-mbp152

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/fsouza/opt/neovim/share/nvim"

Run :checkhealth for more info
```

### PR DESCRIPTION
**Pull request by vigoux**
Abuse a bit of tbl_extend and tbl_deep_extend.
We might want to continue this effort, and simplify this part of the
plugin.

Fixes #178

### CODE REVIEW

File: lua/nvim-treesitter/configs.lua [hunk 1]
```diff
@@ -301,15 +302,7 @@ function M.setup_module(mod, data, mod_name)
...
-      if mod.keymaps.inverse_mappings then
-        mod.keymaps = data.keymaps
-      else
-        for f, map in pairs(data.keymaps) do
-          if mod.keymaps[f] then
-            mod.keymaps[f] = map
-          end
-        end
-      end
+      mod.keymaps = vim.tbl_extend("force", mod.keymaps, data.keymaps)
```
Comment (theHamsta) [inline lua/nvim-treesitter/configs.lua:305]: that was also my first solution. I don't remember why I dropped it.

**Comment by theHamsta** [comment]
Does this also fix #179 ?

**Comment by vigoux** [comment]
> Does this also fix #179 ? probably not.

Nope, but I am working on it. Should be simple though.
