### PR TITLE
refacto/fix: filetype / parser name distinction

### LINKED ISSUE #84: parsers not recognized/working for tsx files and csharp files
a first easy way to fix this is to check for the filetype and change it when needed.

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes #84.

- move parser list in `parsers.lua`. All the code related to the parser is now basically in parsers.lua
- most `ft` variables have been renamed to `lang`, and the switch between those is easier to do with two function:
   - `parsers.ft_to_lang(ft) -> lang`
   - `parsers.lang_to_ft(lang) -> ft`
- filetypes are now only used when binding autocmd to Filetype on start and on commands like `TSBufEnable` and such. Otherwise, we use the `lang` to match the parser name we want. In the parser list, if a parser name does not match its filetype, we define a key `filetype`.

### CODE REVIEW

File: lua/nvim-treesitter/configs.lua [hunk 1]
```diff
@@ -139,9 +139,9 @@ parserlist.typescript = {
   }
 }
 
-parserlist.tsx = {
+parserlist.typescriptreact = {
   install_info = {
```
Comment (theHamsta) [inline lua/nvim-treesitter/configs.lua:143]: Needs to be changed also in base language map.

Comment (kyazdani42) [reply lua/nvim-treesitter/configs.lua:143]: indeed, this is a very much WIP PR until i can make some changes into neovim's core !

Comment (kyazdani42) [reply lua/nvim-treesitter/configs.lua:143]: actually found that neovims core might just work quite fine. I will fix the issues in this PR instead

**Comment by vigoux** [comment]
LGTM, it is good to have some consistency, I will review this more heavily later, but it looks good

File: lua/nvim-treesitter/parsers.lua [hunk 2]
```diff
@@ -1,17 +1,255 @@
...
+        url = "https://github.com/tree-sitter/tree-sitter-regex",
+        files = { "src/parser.c" }
+    }
+}
+
+local M = {
+  list = list
+}
+
+local ft_to_parsername = {}
```
Comment (theHamsta) [inline lua/nvim-treesitter/parsers.lua:218]: This dictionary should be made somehow accessible for configuration for users. In case, they want to use a parser from a mainstream language for niche-dialect.

Comment (kyazdani42) [reply lua/nvim-treesitter/parsers.lua:218]: Maybe the users could setup their own parsers ? they don't need to access this particular variable if they setup new parsers directly in the `list`

Comment (kyazdani42) [reply lua/nvim-treesitter/parsers.lua:218]: well this should not be available actually, because you cannot setup new parsers just editing this dict. I'm going to add some code to make this possible though.

**Comment by kyazdani42** [comment]
I think adding this should be in another PR as it will involve a little bit of code and thinking, i don't want to pollute this PR with other features :)

File: lua/nvim-treesitter/configs.lua [hunk 3]
```diff
@@ -242,81 +35,89 @@ local config = {
...
+  if not lang then
+    return
+  end
+
+  if not parsers.list[lang] or not config.modules[mod] then
     return
   end
 
   local loaded_mod = require(string.format("nvim-treesitter.%s", mod))
   loaded_mod.detach(bufnr, ft)
```
Comment (theHamsta) [inline lua/nvim-treesitter/configs.lua:98]: @kyazdani42 there are still a few occurrences of  'ft' left! ft is undefined here.

Comment (theHamsta) [reply lua/nvim-treesitter/configs.lua:98]: Also in `M.is_enabled`

Comment (theHamsta) [reply lua/nvim-treesitter/configs.lua:98]: Also `locals.lua` needs to be updated (ft -> lang). Just seeing this now when playing a bit with nvim-treesitter.

Comment (kyazdani42) [reply lua/nvim-treesitter/configs.lua:98]: woops sorry guys i thought you reviewed the code before that !
I will push an update thanks for notifying

Comment (theHamsta) [reply lua/nvim-treesitter/configs.lua:98]: Reviewing was looking at the code and test some basic functionality. Disabling is not triggered that often. But the linters see it. With proper CI this will not happen in future.
