### PR TITLE
fix: off-by-one errors in indent calculation

### LINKED ISSUE #1987: The last line of node marked as @ignore is still re-indented
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Even though a node is marked as `@ignore`, the last line of its span is still re-indented. But it should be ignored.
Is there a off-by-one error?

It seems this issue is mentioned by @kyazdani42 in https://github.com/nvim-treesitter/nvim-treesitter/pull/987#pullrequestreview-601225690 but is still not fixed.

### To Reproduce

1. `set ft=javascript`
2. 
```javascript
var foo = `
  some
      random
    indent
      last`;
```
3. `gg=G`
4.
```javascript
var foo = `
  some
      random
    indent
last`;
```

### Expected behavior

```javascript
var foo = `
  some
      random
    indent
      last`;
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.18.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { "gcc", "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (GCC) 10.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - html           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - nix            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

```

### Output of `nvim --version`

```text
(Built from git 03b805aee617f67eb7f33a54822bc76c23a2c5f5)

NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/c3qkhbicjp5q3mx4b5slhzp4w7h6m8yx-neovim-unwrapped-20211106/share/nvim
"

Run :checkhealth for more info

```

### Additional context

It's not about a specific language. It also exists in lua comment and my own queries.

### PR DESCRIPTION
**Pull request by oxalica**
Fix #1987

Python tests have covered this, especially https://github.com/nvim-treesitter/nvim-treesitter/blob/63a88c873f3643aad9208488765dc53618edd40e/tests/indent/python/strings.py#L13-L17

### CODE REVIEW

File: tests/indent/python_spec.lua [hunk 1]
```diff
@@ -13,14 +13,10 @@ describe("indent Python:", function()
...
       expected_failures = {
         "./aligned_indent.py",
-        "./basic_blocks.py",
         "./branches.py",
-        "./control_flow.py",
         "./hanging_indent.py",
         "./join_lines.py",
         "./nested_collections.py",
-        "./strings.py",
-        "./control_flow.py",
```
Comment (theHamsta) [inline tests/indent/python_spec.lua:23]: wow, nice!

**Review by kyazdani42 — APPROVED** [review]
thanks :)
