### PR TITLE
fix: node_incremental for incremental selection jumping around

### LINKED ISSUE #3255: node_incremental for incremental selection jumping around
### Describe the bug

When I hit the key mapped to `node_incremental`, I'm put back in Normal mode, the cursor jumps to the end of the file, and a new line is inserted somewhere in the file.

### To Reproduce

1. Hit key mapped to `init_selection` (this works as expected).
2. Hit key mapped to `node_incremental`.
3. See described behavior.

### Expected behavior

The visual selection to increment to the next node.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - go             ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - zig            ✓ . ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - tsx            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
           +) multiple parsers found, only one will be used
           x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev-762-g0a049c322
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jaco@roshar

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

I've tried recompiling Neovim from the stable branch, remapping the keymap for  `node_incremental`, but nothing seems to work. This worked before yesterday.

### PR DESCRIPTION
**Pull request by itepechi**
Fixes #3255

### CODE REVIEW

**Review by kyazdani42 — APPROVED** [review]
this change is better than https://github.com/nvim-treesitter/nvim-treesitter/pull/3256, closing the other one, thanks :)

File: lua/nvim-treesitter/incremental_selection.lua [hunk 1]
```diff
@@ -131,15 +131,19 @@ function M.attach(bufnr)
   local config = configs.get_module "incremental_selection"
   for funcname, mapping in pairs(config.keymaps) do
     local mode
+    local rhs
     if funcname == "init_selection" then
       mode = "n"
+      rhs = M[funcname]
     else
       mode = "x"
+      -- We need to move to command mode to access marks '< (visual area start) and '> (visual area end) which are not properly accessible in visual mode.
```
Comment (argshook) [inline lua/nvim-treesitter/incremental_selection.lua:140]: `luacheck` is complaining that this comment is too long

```suggestion
      -- We need to move to command mode to access marks '< (visual area start) and '> (visual area end) which are not
      -- properly accessible in visual mode.
```
