### PR TITLE
update installer with sync and some fixes

### LINKED ISSUE #111: Add sync option to TSInstall
TSInstall runs asynchronous backend, but in headless install mode, it needs a way to exit when all installations are done.
`nvim --headless ' +TSInstall -sync all' +qa`
with `-sync` option or any other symbal to represent "synchronous" meaning, the `+qa` command will excute after `+TSInstall all` done

### LINKED ISSUE #124: Support lua 5.1
**Describe the bug**
the plugin fails to load with the following error
```
Error detected while processing $HOME/.local/share/nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.vim:
line   20:
E5108: Error executing lua error loading module 'nvim-treesitter.install' from file '$HOME/.local/share/nvim/plugged/nvim-treesitter/lua/nvim-treesitter/install.lua':
        ...local/share/nvim/plugged/nvim-treesitter/lua/nvim-treesitter/install.lua:110: '=' expected near 'continue'
```
`git bisect` reveals 0ed1fbf9093a7dda9aadda145c1b35dc5343cc8b to be the first bad commit
`lua -v` : Lua 5.1.5
**To Reproduce**
install nvim-treesitter (using vim-plug in my case)

**Expected behavior**
neovim should start without errors

**Output of `:checkhealth nvim_treesitter` **

```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `locals.scm` found.
  - OK: `highlights.scm` found.

## Missing parsers
  - WARNING: Some parsers are not installed:
    typescript
    haskell
    json
    ocaml
    regex
    ruby
    rust
    yaml
    swift
    html
    java
    cpp
    scala
    vue
    lua
    nix
    php
    markdown
    julia
    css
    elm
    tsx
    python
    c_sharp
    javascript
    toml
    bash
    go
    - ADVICE:
      - Install them using `:TSInstall language
```

**Output of `nvim --version`**

```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_aWOCt/neovim-0.5.0+ubuntu1+git202006281322-48ac77a-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_M -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-_aWOCt/neovim-0.5.0+ubuntu1+git202006281322-48ac77a-00e710e/build/config -I/build/neovim-_aWOCt/neovim-0.5.0+ubuntu1+git202006281322-48ac77a-00e710e/src -I/build/neovim-_aWOCt/neovim02006281322-48ac77a-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-_aWOCt/neovim-0.5.0+ubuntu1+git202006281322-48ac77a-00e710e/build/src/nvim/auto -I/build/neovim-_aWOCt/neovim-0.5.0+ubuntu1+git202006281322-48ac77a-00e710e/build/inc
Compiled by buildd@lgw01-amd64-017

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### PR DESCRIPTION
**Pull request by kyazdani42**
- add sync method for installing using `system`
- remove `descriptions` in command configs
- use install(lang) in ensure_installed and make it compatible

fixes #111 
fixes #124 (the function call is ugly but idk right now)

### CODE REVIEW

File: lua/nvim-treesitter/install.lua [hunk 1]
```diff
@@ -76,83 +111,81 @@ local function run_install(cache_folder, package_path, lang, repo)
...
-  if ... == 'all' then
-    languages = parsers.available_parsers()
-    check_installed = false
-  end
+    local languages = vim.tbl_flatten({...})
+    local ask_reinstall = true
+    if ... == 'all' then
+      languages = parsers.available_parsers()
+      ask_reinstall = false
+    end
```
Comment (vigoux) [inline lua/nvim-treesitter/install.lua]: Can we change that to:
```suggestion
    local languages
    local ask_reinstall
    if ... == 'all' then
      languages = parsers.available_parsers()
      ask_reinstall = false
    else
      languages = vim.tbl_flatten({...})
      ask_reinstall = true
    end
```
 I find it easier to read...
