### PR TITLE
refacto: deprecate used_by in parsers.lua

### LINKED ISSUE #2373: Parsers used_by doesn't work for html parser
### Describe the bug

I am trying to use the html parser to for other filetypes (e.g. htmldjango) and am not having success. When I set the parsers used_by in my `init.lua`, it doesn't seem to work for the html parser, for example:

```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.html.used_by = "text"
```
doesn't work, but if I do the same with the python parser:

```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.python.used_by = "text"
```
then it behaves as expected (using "text" as an example filetype).

### To Reproduce

1. Add the following to `init.lua`
```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.html.used_by = "text"
```
2. Open a blank filetype="text" file in neovim (e.g test.txt), and check if treesitter is working.

### Expected behavior

Treesitter should work as it does when opening an html file.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (714bfd47a744ab44b904375c177a24c0614ef49c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.0.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 10.2.1-6) 10.2.1 20210110
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - clojure        ✓ ✓ ✓ . ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - gowork         ✓ . . . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - vue            ✓ . ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - fortran        ✓ . ✓ ✓ . 
  - erlang         . . . . . 
  - pioasm         ✓ . . . ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - elm            ✓ . . . ✓ 
  - haskell        ✓ . . . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - eex            ✓ . . . ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - prisma         ✓ . . . . 
  - rasi           ✓ ✓ ✓ ✓ . 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - foam           ✓ ✓ ✓ ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - swift          ✓ ✓ . . . 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - norg           . . . . . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - d              ✓ . ✓ ✓ ✓ 
  - hocon          ✓ . . . ✓ 
  - make           ✓ . . . ✓ 
  - http           ✓ . . . ✓ 
  - llvm           ✓ . . . . 
  - commonlisp     ✓ ✓ ✓ . . 
  - hack           ✓ . . . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - json5          ✓ . . . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - cmake          ✓ . ✓ . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - r              ✓ ✓ . . . 
  - scss           ✓ . . ✓ . 
  - nix            ✓ ✓ ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - jsdoc          ✓ . . . . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - scala          ✓ . ✓ . ✓ 
  - verilog        ✓ ✓ ✓ . ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - perl           ✓ . . . . 
  - dockerfile     ✓ . . . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - phpdoc         ✓ . . . . 
  - gomod          ✓ . . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - glimmer        ✓ . . . . 
  - json           ✓ ✓ ✓ ✓ . 
  - pug            ✓ . . . ✓ 
  - regex          ✓ . . . . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+923-gecec95712
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-624

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kyazdani42**
TODO: should i create a public function to modify this list instead of providing the user with the table ?

- remove print_warning function from utils.lua (unused)
- cleanup some functions in parsers.lua (shadowing parameters and wrong
  bufnr used).
- log a deprecation notice when using used_by in a parser definition
- default the filetype_to_parsername table to the list of filetypes
  previously in the used_by keys
- update the README to indicate that change

fixes #2373

### CODE REVIEW

File: lua/nvim-treesitter/parsers.lua [hunk 1]
```diff
@@ -971,8 +971,8 @@ end
 
 M.reset_cache()
 
-function M.has_parser(lang)
-  local lang = lang or M.get_buf_lang(api.nvim_get_current_buf())
+function M.has_parser(_lang)
+  local lang = _lang or M.get_buf_lang(api.nvim_get_current_buf())
```
Comment (theHamsta) [inline lua/nvim-treesitter/parsers.lua:975]: I would rather remove the "not shadow" rule from .luacheckrc or do `lang = lang or` without the local. I personally think the "not shadow" rule is a anti-pattern since it prevents you from hiding another variable name that's not relevant in this context

**Comment by theHamsta** [comment]
Can you also post this in #2293 after merge?

**Review by clason — APPROVED** [review]
