### PR TITLE
fix(indent): set only one autocmd for binding indentexpr

### LINKED ISSUE #3172: indentexpr autocmd is added repeatedly on lua Filetype
### Describe the bug

Issuing `:au FileType` command reveals the same autocommand appears repeatedly for lua Filetype:

```
FileType
    lua       setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
              setlocal indentexpr=nvim_treesitter#indent()
```

The number of `setlocal ...` expressions in the list appears to be one per lua file that has been opened.

### To Reproduce

1. Open vim.
2. Open a few lua files
3. type `:au FileType` while in normal mode.
4. inspect the "ungrouped" FileType area of the output for lua (shows up at the very bottom for me).

### Expected behavior

I would expect the `setlocal indentexpr` command to run exactly once on each `FileType=lua` event.

### Output of `:checkhealth nvim-treesitter`

```markdown
:) $ nvim --version                                                                                                                                                                                                             !12607
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```


### Output of `nvim --version`

```text
:) $ nvim --version                                                                                                                                                                                                             !12607
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```


### Additional context

The following fix worked for me, adding an augroup to contain the autocmd where the augroup is cleared on each call:

At https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/indent.lua#L198-L201

```lua
function M.attach(bufnr)
  indent_funcs[bufnr] = vim.bo.indentexpr
  vim.bo.indentexpr = "nvim_treesitter#indent()"
  vim.api.nvim_create_autocmd(
    "Filetype",
    {
      pattern = vim.bo.filetype,
      command = "setlocal indentexpr=nvim_treesitter#indent()",
      group = vim.api.nvim_create_augroup("LuaIndent", {clear = true}),
    }
  )
end
```

### PR DESCRIPTION
**Pull request by kyazdani42**
Seems like the configs module already setup the filetype autocmd to attach, so this autocmd is not needed at all.
fixes #3172

### CODE REVIEW

File: lua/nvim-treesitter/indent.lua [hunk 1]
```diff
@@ -192,13 +192,34 @@ end
 
 local indent_funcs = {}
 
+local augroup = vim.api.nvim_create_augroup("Treesitter-indents", {})
```
Comment (theHamsta) [inline lua/nvim-treesitter/indent.lua:195]: Is `-` ok now for those indentifiers?

File: lua/nvim-treesitter/indent.lua [hunk 2]
```diff
@@ -192,13 +192,34 @@ end
...
+  autocmd_id = vim.api.nvim_create_autocmd("Filetype", {
+    group = augroup,
+    pattern = filetypes,
+    callback = function()
+      vim.bo.indentexpr = "nvim_treesitter#indent()"
+    end,
+  })
+end
+
 function M.attach(bufnr)
```
Comment (theHamsta) [inline lua/nvim-treesitter/indent.lua:219]: shouldn't this functionality not handled on module level? The module interface could have a method that runs only once one `setup` or `init_module` or when the module is first attached for a specific filetype

File: lua/nvim-treesitter/indent.lua (hunk 1 above)
Comment (kyazdani42) [reply lua/nvim-treesitter/indent.lua:195]: seems to be yes

File: lua/nvim-treesitter/indent.lua (hunk 2 above)
Comment (kyazdani42) [reply lua/nvim-treesitter/indent.lua:219]: i think it would be better, but since it was like this, i did not want to start a refactoring for this, this is just a temporary fix.

Comment (kyazdani42) [reply lua/nvim-treesitter/indent.lua:195]: @theHamsta i removed it since after exploring a bit, i've noticed the autocmd is already set by the configs module.

**Review by theHamsta — APPROVED** [review]
